# Importing Numpy

In [1]:
import numpy as np

# Creating an array

In [2]:
arr = np.arange(20).reshape(4,5)

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 1- Calculating Squareroot 

In [4]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

# 2- Exponent

In [6]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08]])

# 3- Logarithm

In [7]:
np.log(arr)

C:\Users\GOHAR\AppData\Local\Temp\ipykernel_6400\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898]])

In [8]:
np.log10(arr)

C:\Users\GOHAR\AppData\Local\Temp\ipykernel_6400\2153533263.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([[      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251],
       [1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804],
       [1.17609126, 1.20411998, 1.23044892, 1.25527251, 1.2787536 ]])

In [9]:
np.log2(arr)

C:\Users\GOHAR\AppData\Local\Temp\ipykernel_6400\1405652587.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)


array([[      -inf, 0.        , 1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ],
       [3.32192809, 3.45943162, 3.5849625 , 3.70043972, 3.80735492],
       [3.9068906 , 4.        , 4.08746284, 4.169925  , 4.24792751]])

# 4- Checking Sign on Each value

In [10]:
np.sign(arr)

array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 5- Arithematic Operations

# Sum

In [13]:
np.sum(arr)

190

# Add

In [14]:
np.add(arr,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Substract

In [16]:
np.subtract(arr,5)

array([[-5, -4, -3, -2, -1],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Multiply

In [17]:
np.multiply(arr,5)

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

# Divide

In [19]:
np.divide(arr,5)

array([[0. , 0.2, 0.4, 0.6, 0.8],
       [1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8],
       [3. , 3.2, 3.4, 3.6, 3.8]])

# Power

In [24]:
np.power(arr,4)

array([[     0,      1,     16,     81,    256],
       [   625,   1296,   2401,   4096,   6561],
       [ 10000,  14641,  20736,  28561,  38416],
       [ 50625,  65536,  83521, 104976, 130321]], dtype=int32)

# Mod

In [23]:
np.mod(arr,3)

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1]], dtype=int32)

# 6- Maximum and Minimum

In [25]:
np.max(arr)

19

In [26]:
np.min(arr)

0

# 7- Null not Null

In [35]:
np.isnan(arr)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# 8-Mean median mode and stdeviation

In [38]:
np.mean(arr)

9.5

In [39]:
np.median(arr)

9.5

In [43]:
np.modf(arr)

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]))

In [44]:
np.std(arr)

5.766281297335398

# 9- Ceil and floor

In [46]:
arr = np.arange(0.1,10.5)

In [47]:
np.ceil(arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [48]:
np.floor(arr)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# 10- Rint

In [49]:
np.rint(arr)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# 11- Percentile

In [53]:
np.percentile(arr, 10)

1.1

# 12- Average

In [54]:
np.average(arr)

5.1000000000000005

# 13 - Repeat

In [58]:
np.repeat(4,5)

array([4, 4, 4, 4, 4])

# 14 - argmax and argmin

In [59]:
np.argmax(arr)

10

In [60]:
np.argmin(arr)

0

# 15 - Uniform

In [63]:
arr = np.random.uniform(5,15,8)

In [64]:
arr

array([14.12929625, 13.20342599,  6.29425736, 10.95603454, 12.97849751,
        7.13668594, 12.24120809, 11.15025706])

# 16- Unique

In [65]:
np.unique(arr)

array([ 6.29425736,  7.13668594, 10.95603454, 11.15025706, 12.24120809,
       12.97849751, 13.20342599, 14.12929625])

# 17- Squeeze

In [73]:
arr = np.arange(4*4).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
np.squeeze(arr)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# 18- Union

In [75]:
arr = np.arange(3)

In [76]:
arr1 = np.arange(2,6)

In [77]:
np.union1d(arr,arr1)

array([0, 1, 2, 3, 4, 5])

# 19 - Equals

In [82]:
arr1.shape

(4,)

In [83]:
arr.shape

(3,)

In [86]:
arr = np.append(arr, 8)

In [87]:
np.equal(arr, arr1)

array([False, False, False, False])

# 20 - Copy

In [88]:
a = arr.copy()

In [89]:
a

array([0, 1, 2, 8])