# Importing Numpy

In [2]:
import numpy as np

# Creating 1D Array

In [3]:
arr = np.array([2,4,6,8])
arr

array([2, 4, 6, 8])

# Creating 2D Array

In [4]:
arr = np.array([[1,3,5,7],[2,4,6,8]])
arr

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

# Creating 3D Array

In [5]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

# Creating Array using Arange

In [6]:
arr = np.arange(10)  #1D array
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.arange(10*10).reshape(10,10) #2D array
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
arr  = np.arange(5*10*10).reshape(5,10,10) # 3D array
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

# Zeros Array

In [9]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr = np.zeros(64).reshape(8,8)
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr = np.zeros(10*2*2).reshape(10,2,2)
arr

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

# Ones Array

In [12]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
arr = np.ones(12*12).reshape(12,12)
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.ones(4*10*10).reshape(4,10,10)
arr

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

# Creating empty array

In [15]:
arr = np.empty(3*6*6).reshape(3,6,6)
arr

array([[[1.05497652e-311, 1.05491725e-311, 1.05497652e-311,
         1.05491725e-311, 1.05497652e-311, 1.05491725e-311],
        [1.05497652e-311, 1.05491725e-311, 1.05497652e-311,
         1.05491725e-311, 1.05497652e-311, 1.05491725e-311],
        [1.05497652e-311, 1.05491725e-311, 1.05497652e-311,
         1.05491725e-311, 1.05497652e-311, 1.05491725e-311],
        [1.05497652e-311, 1.05491725e-311, 1.05491725e-311,
         1.05497652e-311, 1.05491725e-311, 1.05497652e-311],
        [1.05491725e-311, 1.05497652e-311, 1.05491725e-311,
         1.05497652e-311, 1.05491725e-311, 1.05497652e-311],
        [1.05491725e-311, 1.05497652e-311, 1.05491725e-311,
         1.05497652e-311, 1.05491725e-311, 1.05497652e-311]],

       [[1.05491725e-311, 1.05497652e-311, 1.05491725e-311,
         1.05497652e-311, 1.05491725e-311, 1.05491725e-311],
        [1.05497652e-311, 1.05491725e-311, 1.05497652e-311,
         1.05491725e-311, 1.05497652e-311, 1.05491725e-311],
        [1.05497652e-311, 1.05


# Creating linespace array

In [16]:
arr = np.linspace(0,10,6)
arr

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [17]:
arr = np.linspace(10,110,100).reshape(10,10)
arr

array([[ 10.        ,  11.01010101,  12.02020202,  13.03030303,
         14.04040404,  15.05050505,  16.06060606,  17.07070707,
         18.08080808,  19.09090909],
       [ 20.1010101 ,  21.11111111,  22.12121212,  23.13131313,
         24.14141414,  25.15151515,  26.16161616,  27.17171717,
         28.18181818,  29.19191919],
       [ 30.2020202 ,  31.21212121,  32.22222222,  33.23232323,
         34.24242424,  35.25252525,  36.26262626,  37.27272727,
         38.28282828,  39.29292929],
       [ 40.3030303 ,  41.31313131,  42.32323232,  43.33333333,
         44.34343434,  45.35353535,  46.36363636,  47.37373737,
         48.38383838,  49.39393939],
       [ 50.4040404 ,  51.41414141,  52.42424242,  53.43434343,
         54.44444444,  55.45454545,  56.46464646,  57.47474747,
         58.48484848,  59.49494949],
       [ 60.50505051,  61.51515152,  62.52525253,  63.53535354,
         64.54545455,  65.55555556,  66.56565657,  67.57575758,
         68.58585859,  69.5959596 ],
       [ 7

# args in numpy

In [18]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

argmax

In [19]:
arr.argmax()

19

argmin

In [20]:
arr.argmin()

0

argsort

In [21]:
arr.argsort() #sorts by index of array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [22]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
arr.argmax()

99

In [24]:
arr[1].argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [25]:
arr = np.random.randint(0,10,(1,10))
arr

array([[7, 6, 3, 6, 0, 8, 1, 4, 3, 3]])

In [26]:
np.argsort(arr)

array([[4, 6, 2, 8, 9, 7, 1, 3, 0, 5]], dtype=int64)

# Array Concatenation

In [28]:
arr = np.arange(4*4).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
arr1 = np.arange(16,32).reshape(4,4)
arr1

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [34]:
arr3 = np.concatenate((arr, arr1))
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [36]:
# for concatenating column wise
arr3 = np.concatenate((arr, arr1),axis = 1)
arr3

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [37]:
# concatenation with stack , hstack and vstack

In [39]:
arr = np.arange(0,10).reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [42]:
arr2 = np.arange(11, 21).reshape(5,2)
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [45]:
np.stack((arr, arr2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [46]:
np.stack((arr,arr2),axis = 1)

array([[[ 0,  1],
        [11, 12]],

       [[ 2,  3],
        [13, 14]],

       [[ 4,  5],
        [15, 16]],

       [[ 6,  7],
        [17, 18]],

       [[ 8,  9],
        [19, 20]]])

In [47]:
# hstack concatenates the arrays horizontally
np.hstack((arr , arr2))

array([[ 0,  1, 11, 12],
       [ 2,  3, 13, 14],
       [ 4,  5, 15, 16],
       [ 6,  7, 17, 18],
       [ 8,  9, 19, 20]])

In [48]:
# vstack concatenates the arrays vertically
np.vstack((arr ,arr2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

# Addition Substraction Multiplication and Division

In [49]:
arr = np.arange(0,4).reshape(2,2)
arr

array([[0, 1],
       [2, 3]])

In [51]:
arr1 = np.arange(5,9).reshape(2,2)
arr1

array([[5, 6],
       [7, 8]])

In [55]:
display(arr.sum())
arr1.sum()

6

26

In [57]:
np.sum((arr, arr1))

32

In [60]:
display(arr)
display(arr1)
display("The addition of array is")
np.sum((arr, arr1),axis = 0)

array([[0, 1],
       [2, 3]])

array([[5, 6],
       [7, 8]])

'The addition of array is'

array([[ 5,  7],
       [ 9, 11]])

In [61]:
display(arr)
display(arr1)
np.sum((arr , arr1), axis = 1)

array([[0, 1],
       [2, 3]])

array([[5, 6],
       [7, 8]])

array([[ 2,  4],
       [12, 14]])

In [63]:
np.multiply(arr , arr1)

array([[ 0,  6],
       [14, 24]])

In [64]:
np.divide(arr , arr1)

array([[0.        , 0.16666667],
       [0.28571429, 0.375     ]])

In [65]:
np.subtract(arr, arr1)

array([[-5, -5],
       [-5, -5]])

# Array Slicing

In [66]:
arr = np.arange(0,20).reshape(4,5)

In [67]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
arr[1][1]

6

In [72]:
arr[1][2]

7

In [71]:
arr[3][2]

17

In [73]:
arr[2]

array([10, 11, 12, 13, 14])

In [75]:
arr[::3]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [76]:
arr[[0,3,0,3,2]]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

# Boolean Slicing

In [80]:
arr = np.arange(20)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
arr%2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [83]:
arr[arr%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [85]:
arr[arr%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18])

In [94]:
arr[(arr%2 == 0) & (arr%3 == 0)]

array([ 0,  6, 12, 18])

In [95]:
a = arr.copy()

In [96]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [99]:
print(id(arr))
print(id(a))

2135304699792
2135307072208


In [100]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [101]:
a[5] = 10
a

array([ 0,  1,  2,  3,  4, 10,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Finding Maximum values between two arrays

In [5]:
arr =  np.arange(0,4).reshape(2,2)
display(arr)
arr1 = np.arange(4,8).reshape(2,2)
arr1

array([[0, 1],
       [2, 3]])

array([[4, 5],
       [6, 7]])

In [7]:
np.maximum(arr , arr1)

array([[4, 5],
       [6, 7]])

# Transposing array

In [8]:
arr = np.arange(3*4).reshape(3,4)

In [9]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Flatten and ravel in array

In [11]:
arr = np.arange(2*5).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
arr = arr.flatten()

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr.ravel()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# finding values in array

In [20]:
2 in [1,2,3,4,5]

True

In [21]:
2 in [1,3,4,5,6]

False

In [22]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr1 = np.linspace(1,20,10)
arr1

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [25]:
arr1 = arr1.astype(int)

In [26]:
arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20])

In [27]:
arr in arr1

C:\Users\GOHAR\AppData\Local\Temp\ipykernel_12208\1031157156.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  arr in arr1


False

In [30]:
arr2 = []
for i in arr:
    if i in arr1:
        print(i)
        arr2.append(i)
arr2

1
3
5
7
9
11


[1, 3, 5, 7, 9, 11]

In [32]:
arr[arr2 in arr]

C:\Users\GOHAR\AppData\Local\Temp\ipykernel_12208\2902225399.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  arr[arr2 in arr]


array([], shape=(0, 12), dtype=int32)

In [33]:
np. in1d(arr,arr1)

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [34]:
arr[np.in1d(arr,arr1)]

array([ 1,  3,  5,  7,  9, 11])

In [37]:
np.in1d(~arr,arr1)

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [42]:
arr[np.in1d(~arr, arr1)]

array([], dtype=int32)

# Save and load array

In [44]:
arr = np.arange(4*3*3).reshape(4,3,3)

In [45]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [46]:
np.save("array.npy",arr)

In [49]:
ar = np.load("array.npy")

In [50]:
ar

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])